(function(g){var window=this;'use strict';var Fdb=function(a,b){if(!Number.isFinite(a))return String(a);a=String(a);var c=a.indexOf(".");-1===c&&(c=a.length);var d="-"===a[0]?"-":"";d&&(a=a.substring(1));return d+(0,g.JRa)("0",Math.max(0,b-c))+a},Gdb=function(){return{G:"svg",
X:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},W:[{G:"path",X:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]}},Hdb=function(){return{G:"svg",
X:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},W:[{G:"path",X:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]}},Jdb=function(a){"number"===typeof a?(this.date=Idb(a,0,1),S5(this,1)):g.Ia(a)?(this.date=Idb(a.getFullYear(),a.getMonth(),a.getDate()),S5(this,a.getDate())):(this.date=new Date(g.Qa()),a=this.date.getDate(),
this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),S5(this,a))},Idb=function(a,b,c){b=new Date(a,b,c);
0<=a&&100>a&&b.setFullYear(b.getFullYear()-1900);return b},S5=function(a,b){a.getDate()!=b&&a.date.setUTCHours(a.date.getUTCHours()+(a.getDate()<b?1:-1))},T5=function(a,b){g.FQ.call(this,a,{G:"div",
K:"ytp-reminder-menu",X:{role:"menu",tabindex:"-1"},W:[{G:"div",K:"ytp-reminder-menu-contents",W:[{G:"div",K:"ytp-reminder-menu-items"}]}]},100,!0);this.buttonElement=b;this.j=[];this.menuPopupRenderer=void 0;this.items=this.Ba("ytp-reminder-menu-items");this.hide()},Ldb=function(a){var b=Kdb(a),c=0,d={};
for(c=0;c<b.length;d={LH:d.LH},c++){var e=a.j[c];e||(e=new g.U({G:"div",K:"ytp-reminder-menu-item",X:{role:"menuitem",tabindex:"0"},W:[{G:"div",K:"ytp-reminder-menu-item-icon",qa:"{{icon}}"},{G:"div",K:"ytp-reminder-menu-item-label",qa:"{{text}}"}]}),d.LH=c,e.Qa("click",function(l){return function(){var m=l.LH;a.Ab();m=Kdb(a)[m];a.ea("reminderMenuItemClicked",m.serviceEndpoint||m.command)}}(d)),e.Da(a.items),a.j[c]=e);
var f=b[c],h=null;switch(f.icon&&f.icon.iconType){case "NOTIFICATIONS":h=Gdb();break;case "NOTIFICATIONS_NONE":h=Hdb();break;case "NOTIFICATIONS_ACTIVE":h=g.EN()}f=f.text?g.PB(f.text):"";e.update({icon:h,text:f})}for(;c<a.j.length;)a.j.pop().dispose();0===c?a.Ab():a.Qc(a.buttonElement)},Kdb=function(a){return(a.menuPopupRenderer&&a.menuPopupRenderer.items||[]).reduce(function(b,c){c&&c.menuServiceItemRenderer&&b.push(c.menuServiceItemRenderer);
return b},[])},U5=function(a){g.U.call(this,{G:"div",
W:[{G:"button",Ja:["ytp-offline-slate-button","ytp-button"],W:[{G:"div",K:"ytp-offline-slate-button-icon",qa:"{{icon}}"},{G:"div",K:"ytp-offline-slate-button-text",qa:"{{text}}"}]}]});this.F=a;this.upcomingEventReminderButtonRenderer=this.toggleButtonRenderer=null;this.u=void 0;this.C=this.j=null;(this.buttonElement=this.Ba("ytp-offline-slate-button"))&&this.S(this.buttonElement,"click",this.D);this.hide()},Ndb=function(a,b,c){!a.toggleButtonRenderer&&b&&b.toggleButtonRenderer?a.toggleButtonRenderer=
b.toggleButtonRenderer:b&&b.toggleButtonRenderer||(a.toggleButtonRenderer=null);
!a.upcomingEventReminderButtonRenderer&&c&&g.M(c,Mdb)?a.upcomingEventReminderButtonRenderer=g.M(c,Mdb):c&&g.M(c,Mdb)||(a.upcomingEventReminderButtonRenderer=null);V5(a)},V5=function(a){if(a.toggleButtonRenderer){var b=a.toggleButtonRenderer;
if(b.isToggled){var c=b.toggledText?g.PB(b.toggledText):"";a.update({text:c,icon:Odb(b.toggledIcon)})}else c=b.defaultText?g.PB(b.defaultText):"",a.update({text:c,icon:Odb(b.defaultIcon)});a.show()}else a.upcomingEventReminderButtonRenderer?(b=Pdb(a))?(c=b.text?g.PB(b.text):"",a.update({text:c,icon:Odb(b.icon)}),a.show()):a.hide():a.hide()},Rdb=function(a,b,c){a.C||(a.C=new g.nz(a.F.V().Lk));
var d={context:g.Ey(a.C.config_||g.Dy())};g.nC()&&(d.context.clientScreenNonce=g.nC());d.params=c;g.oz(a.C,b,d,{timeout:5E3,onSuccess:function(){a.upcomingEventReminderButtonRenderer&&a.u&&(a.upcomingEventReminderButtonRenderer.currentState=a.u,a.u=void 0)},
onError:function(){Qdb(a)},
onTimeout:function(){Qdb(a)}})},Qdb=function(a){a.toggleButtonRenderer?(a.toggleButtonRenderer.isToggled=!a.toggleButtonRenderer.isToggled,V5(a)):a.upcomingEventReminderButtonRenderer&&(a.u=void 0,V5(a))},Odb=function(a){if(!a)return null;
switch(a.iconType){case "NOTIFICATIONS":return Gdb();case "NOTIFICATIONS_NONE":return Hdb();case "NOTIFICATIONS_ACTIVE":return g.EN();default:return null}},Pdb=function(a){if(!a.upcomingEventReminderButtonRenderer)return null;
var b=a.u||a.upcomingEventReminderButtonRenderer.currentState;a=g.t(a.upcomingEventReminderButtonRenderer.states||[]);for(var c=a.next();!c.done;c=a.next())if((c=g.M(c.value,Sdb))&&c.state===b&&c.button&&g.M(c.button,g.QJ))return g.M(c.button,g.QJ);return null},Tdb=function(a){g.U.call(this,{G:"div",
K:"ytp-offline-slate",W:[{G:"div",K:"ytp-offline-slate-background"},{G:"div",K:"ytp-offline-slate-bar",W:[{G:"span",K:"ytp-offline-slate-icon",W:[{G:"svg",X:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},W:[{G:"path",X:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{G:"circle",X:{cx:"12",cy:"12",r:"3"}}]}]},{G:"span",K:"ytp-offline-slate-messages",W:[{G:"div",K:"ytp-offline-slate-main-text",X:{"aria-label":"{{label}}"},qa:"{{mainText}}"},{G:"div",K:"ytp-offline-slate-subtitle-text",qa:"{{subtitleText}}"}]},{G:"span",K:"ytp-offline-slate-buttons"}]},{G:"button",Ja:["ytp-offline-slate-close-button","ytp-button"],W:[g.zN()]},{G:"button",Ja:["ytp-offline-slate-open-button","ytp-button"],W:[g.yN()]}]});var b=this;this.api=a;this.j=this.u=null;this.background=this.Ba("ytp-offline-slate-background");
this.B=this.Ba("ytp-offline-slate-bar");this.D=new g.bo(function(){g.ko(b.B,"ytp-offline-slate-bar-fade")},15E3);
this.I=!1;this.C=new g.bo(function(){g.ko(b.element,"ytp-offline-slate-collapsed")},15E3);
g.D(this,this.C);g.D(this,this.D);this.countdownTimer=new g.bo(this.JX,1E3,this);this.S(a,"presentingplayerstatechange",this.OX);this.S(a,"livestatedata",this.La);var c=this.Ba("ytp-offline-slate-close-button");this.S(c,"click",function(){g.ko(b.element,"ytp-offline-slate-collapsed")});
c=this.Ba("ytp-offline-slate-open-button");this.S(c,"click",function(){g.mo(b.element,"ytp-offline-slate-collapsed")});
this.hide();c=this.getVideoData();c.getPlayerResponse()&&(c=c.getPlayerResponse().playabilityStatus)&&this.La(c);c=8===this.api.getPresentingPlayerType()&&!this.getVideoData().jl;var d=8===this.api.getPresentingPlayerType();g.oo(this.element,"ytp-offline-slate-premiere-trailer",c);g.oo(this.element,"ytp-offline-slate-hide-background",d);a.N("web_rounded_containers")&&g.ko(this.B,"ytp-rounded-offline-slate")},Udb=function(a,b,c){if(b){var d=null!=b.subtitleText?g.PB(b.subtitleText):"";
c=c?c:null!=b.mainText?g.PB(b.mainText):"";var e,f,h,l;b=null!=(l=null==(e=b.mainText)?void 0:null==(f=e.accessibility)?void 0:null==(h=f.accessibilityData)?void 0:h.label)?l:c;a.update({mainText:c,subtitleText:d,label:b});g.oo(a.element,"ytp-offline-slate-single-text-line",!d);g.oo(a.B,"ytp-offline-slate-bar-hidden",!c&&!d)}},W5=function(a,b){var c=(0,g.N)();
this.module="heartbeat";this.trigger=a;this.j=b;this.B=c},beb=function(a){g.mR.call(this,a);
var b=this;this.J=!1;this.T=0;this.D=!1;this.u=new g.bo(function(){var e=b.player.V(),f=b.getVideoData();X5(b)&&(Vdb(b)?Wdb(b,e,f):(Xdb(b),Ydb(b,e,f)))},0);
this.j=this.heartbeatParams=null;this.C=!1;this.I=new g.Eh(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.ma=new g.nz(void 0);this.Y=this.attestationResponse=void 0;this.utcOffsetMinutes=-(new Jdb).getTimezoneOffset();this.B=new g.JF(this);g.D(this,this.u);g.D(this,this.B);Xdb(this);Zdb(this);this.B.S(a,"heartbeatparams",this.uC);this.B.S(a,"presentingplayerstatechange",this.hZ);this.B.S(a,"videoplayerreset",this.iZ);this.B.S(a,g.HB("heartbeat"),this.onCueRangeEnter);this.C&&this.j&&
$db(this,this.j);var c=new g.FB(1E3,0x7ffffffffffff,{priority:1,namespace:"heartbeat"}),d=new g.FB(0x8000000000000,0x8000000000000,{id:"stream_end",priority:1,namespace:"heartbeat"});a.Pe([c,d]);aeb(this)},aeb=function(a){var b=a.getVideoData();
b.cm&&(b=b.botguardData)&&g.$P(b,a.player.V())},Xdb=function(a){var b=a.getVideoData();
if(b.cm&&(b=new g.IJa(b),g.BP.isInitialized()||3<=a.sequenceNumber)){var c=null;if(b.videoData.nk){var d=g.JJa(b);if(d){c={};var e={};d=d.split("&");d=g.t(d);for(var f=d.next();!f.done;f=d.next())f=f.value.split("="),2===f.length&&(e[f[0]]=f[1]);e.r1a&&(c.webResponse=e.r1a);e.r1c&&(c.error=ceb[Number(e.r1c)]);c.challenge=b.videoData.nk}}a.attestationResponse=c||void 0}},Vdb=function(a){var b=a.getVideoData();
if(!g.bK(a.getVideoData())||b.uR)return!1;if(b.useInnertubeDrmService()&&b.J){a="playready"===b.J.flavor&&b.N("html5_innertube_heartbeats_for_playready");var c="widevine"===b.J.flavor&&b.N("html5_innertube_heartbeats_for_widevine");b=g.IG(b.J)&&b.N("html5_innertube_heartbeats_for_fairplay");return!(a||c||b)}return!0},deb=function(a){if(Vdb(a))return!!a.heartbeatParams;
var b=a.getVideoData();return g.bK(a.getVideoData())&&b.useInnertubeDrmService()&&!b.Zk&&!b.fI?!1:!!b.heartbeatToken},Y5=function(a,b){if(!a.u.isActive()&&a.J){var c=a.getVideoData();
if(deb(a)||c.isLivePlayback){if(void 0===b)if(a.D)if(a.C)b=7500;else{var d;b=(null==(d=a.heartbeatParams)?0:d.interval)?1E3*a.heartbeatParams.interval:a.getVideoData().qR||6E4}else b=1E3;a.u.start(b)}}},heb=function(a,b,c){b.tm&&(c=g.Yh(c,{internalipoverride:b.tm}));
var d={cpn:b.clientPlaybackNonce};b.contextParams&&(d.context_params=b.contextParams);b.Rb&&(d.kpt=b.Rb);c=g.Yh(c,d);g.rw(c,{format:"RAW",method:"GET",timeout:3E4,onSuccess:function(e){if(!a.u.isActive()&&X5(a)){a.I.reset();a.sequenceNumber++;e=e.responseText;var f=eeb(e);if(f){a.player.Oa("onHeartbeat",f);var h="ok"===f.status?f.stop_heartbeat?2:0:"stop"===f.status?1:"live_stream_offline"===f.status?0:-1}else h=(h=e.match(feb))?"0"===h[1]?0:1:-1;geb(a,f,e,h)}},
onError:function(e){X5(a)&&Z5(a,!0,"net-"+e.status)},
onTimeout:function(){X5(a)&&Z5(a,!0,"timeout")},
withCredentials:!0})},Wdb=function(a,b,c){var d;
if(null!=(d=a.heartbeatParams)&&d.url){var e=g.Yh(a.heartbeatParams.url,{request_id:g.fsa()});c.Aa&&(e=g.Yh(e,{vvt:c.Aa}),c.mdxEnvironment&&(e=g.Yh(e,{mdx_environment:c.mdxEnvironment})));g.pI(b,c.oauthToken).then(function(f){f&&(e=g.Yh(e,{access_token:f}));heb(a,c,e)})}},X5=function(a){var b=a.getVideoData();
return 3===a.player.getPresentingPlayerType()||g.T(a.player.Fb(a.getPlayerType()),4)?!1:deb(a)||b.isLivePlayback?!0:($5(a),!1)},Ydb=function(a,b,c){var d,e={videoId:c.videoId,
sequenceNumber:a.sequenceNumber,heartbeatServerData:null!=(d=a.oa)?d:c.heartbeatServerData};a.Y=a.attestationResponse;c.cm&&(e.attestationResponse=a.Y);var f=g.bQ(c),h;d=null!=(h=f.client)?h:{};d.utcOffsetMinutes=a.utcOffsetMinutes;e.context=f;e.cpn=c.clientPlaybackNonce;if(h="undefined"!==typeof Intl?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)d.timeZone=h;h={heartbeatChecks:[]};if(d=c.getPlayerResponse())c.heartbeatToken&&(e.heartbeatToken=c.heartbeatToken),(d=d.playabilityStatus)&&
(d=d.liveStreamability)&&d.liveStreamabilityRenderer&&h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");c.heartbeatToken&&h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");if(g.hI(b)){h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED");f=ieb(a);d={};null!==f&&(d.clientPlayerPositionUtcMillis=f);var l,m;f=(null==(m=null==(l=a.player.tb())?void 0:g.CR(l))?void 0:m.freePreviewWatchedDuration)||0;0<f&&(d.freePreviewWatchedDuration={seconds:""+f});h.unpluggedParams=d}e.heartbeatRequestParams=
h;c.isLivePlayback&&(l=ieb(a),null!==l&&(e.playbackState||(e.playbackState={}),e.playbackState.playbackPosition={utcTimeMillis:l}));a.player.ea("heartbeatRequest",e);var n={timeout:3E4,onSuccess:function(p){if(!a.u.isActive()&&X5(a)){var q=a.getVideoData(),r=q.cm&&null==a.Y,w;q.cm=!(null==(w=p.heartbeatAttestationConfig)||!w.requiresAttestation)||r;r=p.playabilityStatus;w=JSON.stringify(r)||"{}";p.authenticationMismatch&&a.player.xa("authshear",{});var x=-1;var z=p.playabilityStatus;z&&(a.player.Oa("onHeartbeat",
z),"OK"===z.status?x=p.stopHeartbeat?2:0:"UNPLAYABLE"===z.status?x=1:"LIVE_STREAM_OFFLINE"===z.status&&(x=0));a.sequenceNumber&&-1===x||a.I.reset();a.sequenceNumber++;p.heartbeatServerData&&(a.oa=p.heartbeatServerData);q.hI=p;p.playerCueRanges&&0<p.playerCueRanges.length&&(q.cueRanges=p.playerCueRanges,q.ea("dataupdated"));geb(a,r,w,x)}},
onError:function(p){X5(a)&&Z5(a,!0,"net-"+p.status)},
onTimeout:function(){X5(a)&&Z5(a,!0,"timeout")}};
g.pI(b,g.vK(c)).then(function(p){p&&(n.FR="Bearer "+p);g.oz(a.ma,"player/heartbeat",e,n)})},geb=function(a,b,c,d){-1===d?(b="decode "+g.Bf(c,3),Z5(a,!1,b)):2===d?($5(a),a.D=!0):(a.T=0,a.u.stop(),1===d?(a.D=!1,a.player.Mg("heartbeat.stop",2,a.Nf(c)),g.Ex("heartbeatActionPlayerHalted",jeb(b))):(a.D=!0,c=0,a.C&&b&&(c=$db(a,b),a.player.ea("livestatedata",b)),c?Y5(a,c):Y5(a)))},$db=function(a,b){var c=b.liveStreamability&&b.liveStreamability.liveStreamabilityRenderer,d=!(!c||!(c.switchStreamsImmediately||
c.transitionTiming&&"STREAM_TRANSITION_TIMING_IMMEDIATELY"===c.transitionTiming)),e=keb(c),f=a.getVideoData(),h=a.player.Fb(a.getPlayerType()),l=h.Zc()&&!g.hK(f)&&!a.player.isAtLiveHead(a.getPlayerType());
if(f.V().De()){var m,n=(null==(m=a.player.Be())?void 0:m.lc())||{};n.status=b.status||"";n.dvr=""+ +l;n["switch"]=""+ +d;n.ended=""+ +!(!c||!c.displayEndscreen);a.player.xa("heartbeat",n)}if(l&&!d)return e;d=c&&c.streamTransitionEndpoint&&g.M(c.streamTransitionEndpoint,g.gJ);if("STREAM_TRANSITION_TIMING_AT_STREAM_END"===(c&&c.transitionTiming))a.getVideoData().transitionEndpointAtEndOfStream=d;else{if(l=d)(l=d&&d.videoId)?(a.player.Ln(l,{autonav:"1"},void 0,!0,!0,d,g.vK(a.getVideoData())),a.TF("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE",
"HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",b),l=!0):l=!1;if(l)return e}if("OK"===b.status.toUpperCase()){d=c&&c.broadcastId;l=a.j&&a.j.liveStreamability&&a.j.liveStreamability.liveStreamabilityRenderer&&a.j.liveStreamability.liveStreamabilityRenderer.broadcastId;m=d!==l&&null!=d;if(!f.hlsvp&&!f.wb||m){var p={video_id:f.videoId};f.WI&&(p.is_live_destination="1");a.player.N("web_player_heartbeat_request_watch_next")||(p.disable_watch_next=!0,p.raw_watch_next_response=f.od);
p.autonav_state=f.autonavState;p.oauth_token=f.oauthToken;p.force_gvi=f.qm;p.Kl=f.Kl;f.T&&(p.vss_credentials_token=f.T,p.vss_credentials_token_type=f.fk);f.Aa&&(p.vvt=f.Aa);c=void 0;f.hlsvp||f.wb?m&&(c=new W5("broadcastIdChanged",l+","+d),a.TF("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",b)):(d&&(c=new W5("formatsReceived",""+d)),a.TF("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",b));a.player.loadVideoByPlayerVars(p,
void 0,void 0,void 0,c);return e}a.player.Ag("heartbeat",a.getPlayerType())}c&&c.displayEndscreen&&(a.offlineSlate?(a=a.offlineSlate,a.I=!0,a.ub&&a.api.qz()):g.lM(h)&&(f=(null==(p=a.player.Be())?void 0:p.lc())||{},a.player.xa("hbse",f,!0),a.player.qz(),a.player.Oa("onLiveMediaEnded",b)));return e},keb=function(a){var b=0;
a&&a.pollDelayMs&&(a=Number(a.pollDelayMs))&&(b=a);return b},Z5=function(a,b,c){var d=a.player.V();
if(!a.u.isActive()){a.u.stop();a.T++;var e=b?"heartbeat.net":"heartbeat.servererror";var f=a.getVideoData();if(f.sR||b&&!g.bK(a.getVideoData())&&!deb(a)&&f.isLivePlayback)f=!1;else{var h,l;(null==(l=a.heartbeatParams)?0:l.jz)?h=a.heartbeatParams.jz:h=f.rR||5;f=a.T>=h}f?(g.Ex("heartbeatActionPlayerHalted",b?{enforcedPolicyToHaltOnNetworkFailure:!0}:jeb()),(b=a.getVideoData())&&b.isLivePlayback?a.player.Mg(e,1,"Se ha interrumpido la reproducci\u00f3n del v\u00eddeo. Vuelve a intentarlo.",c):a.player.Mg(e,
1,"Se ha producido un error de licencia con este v\u00eddeo.",c)):(d.N("html5_report_non_fatal_heartbeat_error")&&a.player.Nq(e,{msg:c}),Y5(a,a.I.getValue()),g.Fh(a.I))}},jeb=function(a){var b={enforcedPolicyToHaltOnNetworkFailure:!1};
a&&(b.serializedServerContext=a.additionalLoggingData);return b},$5=function(a){a.T=0;
a.u.stop();a.D=!1;a.sequenceNumber=0},Zdb=function(a){var b=a.getVideoData(),c=a.player.V();
if(b.isLivePlayback)if(g.TG(c.D)){a.C=!0;a.J=!0;if(!g.WH(c)||g.hI(c))a.offlineSlate=new Tdb(a.player),g.D(a,a.offlineSlate),g.DQ(a.player,a.offlineSlate.element,4);(b=b.getPlayerResponse())&&b.playabilityStatus&&(a.j=b.playabilityStatus);var d;"UNPLAYABLE"!==(null==(d=a.j)?void 0:d.status)&&(a.j?(d=keb(a.j.liveStreamability&&a.j.liveStreamability.liveStreamabilityRenderer))?Y5(a,d):Y5(a,7500):Y5(a,1E3))}else a.player.Mg("html5.unsupportedlive",2,"HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1");else g.kb(b.Ka,
"heartbeat")&&a.player.Ag("heartbeat",a.getPlayerType())},ieb=function(a){return(a=a.player.getProgressState(a.getPlayerType()).ingestionTime)&&isFinite(a)?""+Math.floor(1E3*a):null},eeb=function(a){try{var b=JSON.parse(a);
return null!=b?b:void 0}catch(c){}},ceb=["ATTESTATION_ERROR_UNKNOWN",
"ATTESTATION_ERROR_VM_NOT_INITIALIZED","ATTESTATION_ERROR_VM_NO_RESPONSE","ATTESTATION_ERROR_VM_TIMEOUT","ATTESTATION_ERROR_VM_INTERNAL_ERROR"];var leb={DY:["BC","AD"],CY:["Before Christ","Anno Domini"],f0:"JFMAMJJASOND".split(""),z0:"JFMAMJJASOND".split(""),Z_:"January February March April May June July August September October November December".split(" "),y0:"January February March April May June July August September October November December".split(" "),t0:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),B0:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),Q0:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
D0:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),v0:"Sun Mon Tue Wed Thu Fri Sat".split(" "),C0:"Sun Mon Tue Wed Thu Fri Sat".split(" "),g0:"SMTWTFS".split(""),A0:"SMTWTFS".split(""),u0:["Q1","Q2","Q3","Q4"],o0:["1st quarter","2nd quarter","3rd quarter","4th quarter"],kY:["AM","PM"],yY:["EEEE, MMMM d, y","MMMM d, y","MMM d, y","M/d/yy"],H0:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],zY:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],DP:6,
R0:[5,6],EP:5};
leb={DY:["a. C.","d. C."],CY:["antes de Cristo","despu\u00e9s de Cristo"],f0:"EFMAMJJASOND".split(""),z0:"EFMAMJJASOND".split(""),Z_:"enero febrero marzo abril mayo junio julio agosto septiembre octubre noviembre diciembre".split(" "),y0:"enero febrero marzo abril mayo junio julio agosto septiembre octubre noviembre diciembre".split(" "),t0:"ene feb mar abr may jun jul ago sept oct nov dic".split(" "),B0:"ene feb mar abr may jun jul ago sept oct nov dic".split(" "),Q0:"domingo lunes martes mi\u00e9rcoles jueves viernes s\u00e1bado".split(" "),D0:"domingo lunes martes mi\u00e9rcoles jueves viernes s\u00e1bado".split(" "),
v0:"dom lun mar mi\u00e9 jue vie s\u00e1b".split(" "),C0:"dom lun mar mi\u00e9 jue vie s\u00e1b".split(" "),g0:"DLMXJVS".split(""),A0:"DLMXJVS".split(""),u0:["T1","T2","T3","T4"],o0:["1.er trimestre","2.\u00ba trimestre","3.er trimestre","4.\u00ba trimestre"],kY:["a.\u00a0m.","p.\u00a0m."],yY:["EEEE, d 'de' MMMM 'de' y","d 'de' MMMM 'de' y","d MMM y","d/M/yy"],H0:["H:mm:ss (zzzz)","H:mm:ss z","H:mm:ss","H:mm"],zY:["{1}, {0}","{1}, {0}","{1}, {0}","{1}, {0}"],DP:0,R0:[5,6],EP:3};g.k=Jdb.prototype;g.k.FS=leb.DP;g.k.GS=leb.EP;g.k.clone=function(){var a=new Jdb(this.date);a.FS=this.FS;a.GS=this.GS;return a};
g.k.getFullYear=function(){return this.date.getFullYear()};
g.k.getYear=function(){return this.getFullYear()};
g.k.getMonth=function(){return this.date.getMonth()};
g.k.getDate=function(){return this.date.getDate()};
g.k.getTime=function(){return this.date.getTime()};
g.k.getDay=function(){return this.date.getDay()};
g.k.getUTCFullYear=function(){return this.date.getUTCFullYear()};
g.k.getUTCMonth=function(){return this.date.getUTCMonth()};
g.k.getUTCDate=function(){return this.date.getUTCDate()};
g.k.getUTCDay=function(){return this.date.getDay()};
g.k.getUTCHours=function(){return this.date.getUTCHours()};
g.k.getUTCMinutes=function(){return this.date.getUTCMinutes()};
g.k.getTimezoneOffset=function(){return this.date.getTimezoneOffset()};
g.k.set=function(a){this.date=new Date(a.getFullYear(),a.getMonth(),a.getDate())};
g.k.setFullYear=function(a){this.date.setFullYear(a)};
g.k.setYear=function(a){this.setFullYear(a)};
g.k.setMonth=function(a){this.date.setMonth(a)};
g.k.setDate=function(a){this.date.setDate(a)};
g.k.setTime=function(a){this.date.setTime(a)};
g.k.setUTCFullYear=function(a){this.date.setUTCFullYear(a)};
g.k.setUTCMonth=function(a){this.date.setUTCMonth(a)};
g.k.setUTCDate=function(a){this.date.setUTCDate(a)};
g.k.add=function(a){if(a.u||a.j){var b=this.getMonth()+a.j+12*a.u,c=this.getYear()+Math.floor(b/12);b%=12;0>b&&(b+=12);a:{switch(b){case 1:var d=0!=c%4||0==c%100&&0!=c%400?28:29;break a;case 5:case 8:case 10:case 3:d=30;break a}d=31}d=Math.min(d,this.getDate());this.setDate(1);this.setFullYear(c);this.setMonth(b);this.setDate(d)}a.days&&(c=this.getYear(),b=0<=c&&99>=c?-1900:0,a=new Date((new Date(c,this.getMonth(),this.getDate(),12)).getTime()+864E5*a.days),this.setDate(1),this.setFullYear(a.getFullYear()+
b),this.setMonth(a.getMonth()),this.setDate(a.getDate()),S5(this,a.getDate()))};
g.k.equals=function(a){return!(!a||this.getYear()!=a.getYear()||this.getMonth()!=a.getMonth()||this.getDate()!=a.getDate())};
g.k.toString=function(){var a=this.getFullYear(),b=0>a?"-":1E4<=a?"+":"";return[b+Fdb(Math.abs(a),b?6:4),Fdb(this.getMonth()+1,2),Fdb(this.getDate(),2)].join("")+""};
g.k.valueOf=function(){return this.date.valueOf()};var meb=new g.Jp("addUpcomingEventReminderEndpoint");var neb=new g.Jp("removeUpcomingEventReminderEndpoint");var oeb=new g.Jp("updateUpcomingEventReminderButtonStateCommand");var Mdb=new g.Jp("upcomingEventReminderButtonRenderer"),Sdb=new g.Jp("upcomingEventReminderButtonStateRenderer");g.v(T5,g.FQ);T5.prototype.hide=function(){this.buttonElement&&this.buttonElement.removeAttribute("aria-haspopup");g.FQ.prototype.hide.call(this)};
T5.prototype.show=function(){this.buttonElement&&this.buttonElement.setAttribute("aria-haspopup","true");g.FQ.prototype.show.call(this)};
T5.prototype.ra=function(){g.ab(this.j);g.FQ.prototype.ra.call(this)};g.v(U5,g.U);
U5.prototype.D=function(){if(this.toggleButtonRenderer){var a=this.toggleButtonRenderer;a.isToggled?this.B(a.toggledServiceEndpoint):this.B(a.defaultServiceEndpoint);a.isToggled=!a.isToggled;V5(this)}else if(this.upcomingEventReminderButtonRenderer)if(this.j&&this.j.ub)this.j.Ab();else{var b=Pdb(this);b&&this.B(b.serviceEndpoint||b.command);b=(null==(a=g.M(null==b?void 0:b.command,g.oO))?void 0:a.commands)||[];a:{a=g.t(b);for(var c=a.next();!c.done;c=a.next()){var d=b=void 0;if(c=null==(b=g.M(c.value,
g.H7a))?void 0:null==(d=b.popup)?void 0:d.menuPopupRenderer){a=c;break a}}a=void 0}this.j||(this.j=new T5(this.F,this.buttonElement),this.j.Da(this.element),g.D(this,this.j),this.j.subscribe("reminderMenuItemClicked",this.B,this));b=this.j;b.menuPopupRenderer=a;Ldb(b)}};
U5.prototype.B=function(a){var b=g.M(a,meb),c=g.M(a,neb);if(a&&(b||c)){if(b){var d=b;var e="notification/add_upcoming_event_reminder"}else c&&(d=c,e="notification/remove_upcoming_event_reminder");if(e&&d&&d.params)for(Rdb(this,e,d.params),a=g.t(d.commands||[]),b=a.next();!b.done;b=a.next())if((b=b.value)&&g.M(b,oeb)){this.u=g.M(b,oeb).state;V5(this);break}}};g.v(Tdb,g.U);g.k=Tdb.prototype;g.k.getPlayerType=function(){if(8===this.api.getPresentingPlayerType())return 1};
g.k.getVideoData=function(){return this.api.getVideoData(this.getPlayerType())};
g.k.La=function(a){var b,c,d=null==a?void 0:null==(b=a.liveStreamability)?void 0:null==(c=b.liveStreamabilityRenderer)?void 0:c.offlineSlate;if(d){this.u=a;b=d.liveStreamOfflineSlateRenderer;b.canShowCountdown?this.JX():Udb(this,b);var e,f,h,l;if(c=null==a?void 0:null==(e=a.liveStreamability)?void 0:null==(f=e.liveStreamabilityRenderer)?void 0:null==(h=f.offlineSlate)?void 0:null==(l=h.liveStreamOfflineSlateRenderer)?void 0:l.thumbnail){e=0;f=null;h=c.thumbnails;for(l=0;l<h.length;l++)h[l].width>
e&&(e=h[l].width||0,f=h[l].url);f&&(this.background.style.backgroundImage="url("+f+")")}else this.background.style.backgroundImage="";b.actionButtons||b.reminderButton?(this.j||(this.j=new U5(this.api),this.j.Da(this.Ba("ytp-offline-slate-buttons")),g.D(this,this.j)),Ndb(this.j,b.actionButtons&&b.actionButtons[0],b.reminderButton)):this.j&&Ndb(this.j,null,null);this.u=a}else this.u=null;this.OX()};
g.k.OX=function(a){if(8===this.api.getPresentingPlayerType())var b=!0;else{var c=this.api.Fb(),d=this.getVideoData();b=d.isLivePlayback&&(g.lM(c)||g.T(c,2)||g.T(c,64));var e=2===d.autonavState&&g.T(c,2);c=c.Zc()&&!g.hK(d)&&!this.api.isAtLiveHead(void 0,!0);b=b&&!c&&!e}b&&this.u?this.ub?(null==a?0:g.xL(a,2))&&!this.getVideoData().jl&&(g.mo(this.element,"ytp-offline-slate-collapsed"),this.C.stop(),g.mo(this.B,"ytp-offline-slate-bar-fade"),this.D.start()):(this.show(),this.C.start(),this.api.ea("offlineslatestatechange"),
this.I&&this.api.qz()):this.ub&&(this.hide(),this.api.ea("offlineslatestatechange"))};
g.k.JX=function(){var a,b,c,d,e=null==(a=this.u)?void 0:null==(b=a.liveStreamability)?void 0:null==(c=b.liveStreamabilityRenderer)?void 0:null==(d=c.offlineSlate)?void 0:d.liveStreamOfflineSlateRenderer;e&&(a=Math.floor(g.Qa()/1E3),b=e.canShowCountdown&&Number(e.scheduledStartTime),!b||b<=a?(Udb(this,e),this.countdownTimer.stop()):(Udb(this,e,g.vO(b-a)),g.co(this.countdownTimer)))};
g.k.ra=function(){this.countdownTimer.dispose();this.countdownTimer=null;g.U.prototype.ra.call(this)};W5.prototype.u=function(a){return this.trigger&&a.trigger?this.module===a.module&&this.trigger===a.trigger&&this.j===a.j:!1};
W5.prototype.isExpired=function(){return 6E4<(0,g.N)()-this.B};
W5.prototype.toString=function(){return this.module+":"+this.trigger+":"+this.j};g.v(beb,g.mR);g.k=beb.prototype;g.k.ra=function(){$5(this);this.player.eg("heartbeat");g.mR.prototype.ra.call(this)};
g.k.onCueRangeEnter=function(){this.J=!0;Y5(this,2E3)};
g.k.uC=function(a){this.heartbeatParams=a;Y5(this,2E3)};
g.k.hZ=function(a){var b;8!==this.player.getPresentingPlayerType()&&"UNPLAYABLE"!==(null==(b=this.j)?void 0:b.status)&&(g.T(a.state,2)||g.T(a.state,64)?($5(this),this.C&&(this.J=!0,Y5(this,1E3))):(g.T(a.state,1)||g.T(a.state,8))&&Y5(this,2E3))};
g.k.iZ=function(){3!==this.player.getPresentingPlayerType()&&Y5(this,2E3)};
g.k.getPlayerType=function(){if(8===this.player.getPresentingPlayerType())return 1};
g.k.getVideoData=function(){return this.player.getVideoData(this.getPlayerType())};
g.k.Pk=function(a){switch(a){case 4:case 3:return!1}return!0};
g.k.TF=function(a,b,c){a={trigger:a,reason:b};c&&(a.serializedServerContext=c.additionalLoggingData);g.Ex("heartbeatActionPlayerTransitioned",a)};
g.k.Nf=function(a){var b="LICENSE",c=eeb(a);if(c)return c.reason||g.UR[b]||"";(a=a.match(feb))&&(a=Number(a[1]))&&(b=g.gDa(a));return g.UR[b]||""};
g.k.UB=function(){return!!this.offlineSlate&&this.offlineSlate.ub};
var feb=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.lR("heartbeat",beb);})(_yt_player);
